### ISSUE TITLE
NixOS package request

### ISSUE THREAD

**Issue by madfanat** [linkfrg/ignis#11]
### Description

If possible, it would be really great if you could provide a package for NixOS (i.e. home-manager). Thank you.

**Comment by linkfrg** [comment]
I am an arch user and it is very unlikely that I will learn Nix in the near future

**Comment by frdiener** [comment]
I made [this package](https://gist.github.com/frdiener/f9472bd268a40d8ec9ee9e2f2537856a) for version 0.2. You can use that with home-manager.

**Comment by linkfrg** [comment]
#13 has been merged, now you can try to install Ignis (thanks @frdiener for gist)

**Comment by madfanat** [comment]
Thanks @frdiener and @linkfrg!! I guess it seems kinda sorted now ;)

**Comment by linkfrg** [comment]
> Thanks @frdiener and @linkfrg!! I guess it seems kinda sorted now ;)

also thanks @somokill for making the pull request!
