### ISSUE TITLE
Render issues after wake up from suspend

### ISSUE THREAD

**Issue by artinmare** [linkfrg/ignis#15]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

No

### Version

ignis 0.2 78846c57832c70fd971dbcd28ac5d8e70cd09840

### Distro

Arch Linux

### Installation method

Distro package

### Description

First of all, sorry if this is not really the place, kinda new to git and github

I have got this render issues that happens after my laptop is awake from suspend.  This is what happens in my current setup
![screenshot-20241007-214532](https://github.com/user-attachments/assets/c2483355-3ae4-4748-ad8c-6cb768541736)

It also happens on minimal config that I use to test the battery feature on the dev version. 
![screenshot_08102024_011644](https://github.com/user-attachments/assets/62e3c143-a6bc-4ce1-8e45-bc211ec49f86)

The part got clear if either I interact with it or some updating happens to that exact widget. ignis reload does fix the problem, so I'm pretty sure it's not the dotfiles (I can be wrong tho).
![screenshot_08102024_011423](https://github.com/user-attachments/assets/6a230c44-e683-43be-aa16-dc8c92ffcd3c)

Oh and locking the session using `loginctl lock-session` doesn't seems to cause the render issue, so I'm positive it's not hyprlock that causes it.

I have attached the config, css, and log. Hope it helps and sorry it it's a false positve.

### How to reproduce

Suspend the PC (Laptop in my case) and turn it on back again. After login in through hyprlock (the one i use for the lock screen) the static widget would have render issues. 

It's happens everytime I suspend, `ignis reload` fixes the problem. Doesn't happens on first boot or reboot

### Logs, images, videos, config files, CSS/SCSS files (if necessary)

[ignis.log](https://github.com/user-attachments/files/17282455/ignis.log)
[config.py.txt](https://github.com/user-attachments/files/17282479/config.py.txt)
[style.scss.txt](https://github.com/user-attachments/files/17282480/style.scss.txt)

**Comment by linkfrg** [comment]
can not reproduce, there may be problems with your drivers

**Comment by artinmare** [comment]
Seems like it, old laptop with Nvidia MX150, not surprising if the Nvidia driver got problems. I would try to install different drivers and figure out if it fix the problem. Would report back later with an update. Thank you

**Comment by AndreyDeimos** [comment]
https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend maybe?

**Comment by artinmare** [comment]
> https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend maybe?

Hi, thank you for the link provided it was really helpful. I may have found the root cause of the issue. It seems that it would only affect people with laptop that have multiple GPU (iGPU and dGPU).

The problem seems to be in the persistence mode for the Nvidia driver. It seems that the driver would unload the state it had every time there is no client connected to the GPU (which happens when suspend is executed since all client to the GPU would be disconnected). This causes the visual glitch to happens because the state needs to be recalculated.

I fix mine by enabling the legacy persistence mode using this command `nvidia-smi -pm ENABLED` or you can use the new persistence daemon by enabling the  `nvidia-persistenced.service`

This may help https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Driver_persistence

I would report back if I found this issue to reoccur, as for now I believe it's fixed and it's not a bug with the Ignis itself.
