### ISSUE TITLE
Cannot hot reload css

### ISSUE THREAD

**Issue by newor0599** [linkfrg/ignis#18]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

Yes

### Version

 ```
Ignis 0.2 78846c57832c70fd971dbcd28ac5d8e70cd09840
```

### Distro

Arch Linux Hyprland

### Installation method

Distro package

### Description

When `/home/username/.config/ignis/style.css` file got updated/written, ignis will not be able to find the updated css file.
This problem persist with scss too

### How to reproduce

Write anything in a css/scss file

### Logs, images, videos, config files, CSS/SCSS files (if necessary)

FileNotFoundError: Provided style path doesn't exists: '/home/username/.config/ignis/style.css'

**Comment by linkfrg** [comment]
Can you please record a video demonstrating the issue?

**Comment by newor0599** [comment]
https://github.com/user-attachments/assets/bd1a05a8-cb61-4fae-80d9-d9533aa79745

**Comment by linkfrg** [comment]
try saving the file from other editors (e.g., micro, nano, or vscode)

**Comment by newor0599** [comment]
Looks like its a problem with neovim, I tried micro and nano, both of them does not have problem

**Comment by linkfrg** [comment]
should be fixed in 314deeb, i installed neovim and tested it

it looks like neovim is deleting and recreating the file when saving which is causing the problem, so as nuclear solution just ignore all event types except ``"changes_done_hint"`` in ``IgnisApp.__watch_config()``

**Comment by newor0599** [comment]
Thanks for the quick fix, keep up the work ❤️
