### ISSUE TITLE
Floating bar

### ISSUE THREAD

**Issue by makssxwq** [linkfrg/ignis#19]
### Description

add a toggle switch in settings  to switch the bar states: floating and attached.
and are there ways to do this now?

**Comment by linkfrg** [comment]
What bar? What settings? Ignis doesn't provide them, just the tools to make them yourself.

If you're talking about my (dotfiles)[https://github.com/linkfrg/dotfiles], then you have opened an issue in the wrong repository, open an issue in my dotfiles repo.
