### ISSUE TITLE
Wrong documentation for mpris import

### ISSUE THREAD

**Issue by Raumsegler1** [linkfrg/ignis#20]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

No

### Version

 ```
Ignis 0.2 78846c57832c70fd971dbcd28ac5d8e70cd09840
```

### Distro

EndeavourOs

### Installation method

Distro package

### Description

The documentation for mpris is wrong:
- from ignis.service.mpris import MprisService

doesn't work because it needs to be: 

- from ignis.services.mpris import MprisService

**service -> services**
idk if this is wrong because of some update or it was always wrong but its wrong for the version i'm using.
It's wrong on at least these pages:
https://linkfrg.github.io/ignis/stable/user/dynamic_content.html
https://linkfrg.github.io/ignis/stable/api/services/mpris.html (here its even more wrong)

This is my first real bug report so i am sorry if its bad.

### How to reproduce

Try it out with my version of ignis

### Logs, images, videos, config files, CSS/SCSS files (if necessary)

from ignis.service.mpris import MprisService

ModuleNotFoundError: No module named 'ignis.service'

**Comment by newor0599** [comment]
I think what you should do is to make a pull request to fix the typo?

**Comment by linkfrg** [comment]
Be patient, i will fix the typo as soon as possible

**Comment by linkfrg** [comment]
fixed in 0772a28 for the latest docs,
a fix for the stable documentation will come later
