### ISSUE TITLE
Battery bar does not update

### ISSUE THREAD

**Issue by prakharn** [linkfrg/ignis#24]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

No

### Version

Ignis 0.2.dev0
Branch: main
Commit: 424689830e89844abb0d95991e098ad0480a55ae (feat: add UPower Service (#10))

### Distro

Arch Linux x86_64

### Description

Battery percentage does not change after startup and remains frozen. 
I suspect this might be due to the file ~/.config/ignis/services/upower.py not existing.

### How to reproduce

Have the latest dotfiles install along with all said dependencies and do something to let the battery status change (ex:discharge), the ignis bar battery widget does not reflect updated change.

**Comment by gauravsatish** [comment]
Can confirm, I have also had this issue. Didn't have the chance to look into it yet.

**Comment by k-amin07** [comment]
Can confirm, have to do ignis reload every once in a while for it to update. Tried adding polling to the widget but could not make it work.

**Comment by linkfrg** [comment]
Try this code:
```
for i in upower.batteries:
    i.device.connect(
        "notify::percentage", lambda x, y, i=i: print("New percent: ", i.percent)
    )
```
Does it work or not?

**Comment by prakharn** [comment]
It does not. 

I might be missing something so correct me if I'm wrong, but the ignis services folder does not have any file named upower in it, could that not be the source of the issue?

**Comment by linkfrg** [comment]
> I might be missing something so correct me if I'm wrong, but the ignis services folder does not have any file named upower in it, could that not be the source of the issue?

![2024-10-20T23:07:29,369396293+05:00](https://github.com/user-attachments/assets/bcde9ab4-ef2d-47a6-8dfe-2c1431c888dd)
In Ignis source, not dotfiles

**Comment by linkfrg** [comment]
> It does not.

Strange, it seems that UpowerGlib does not automatically notify the percentage

**Comment by k-amin07** [comment]
> Strange, it seems that UpowerGlib does not automatically notify the percentage

shouldnt it be polling the battery periodically? like with the clock?

**Comment by linkfrg** [comment]
> shouldnt it be polling the battery periodically? like with the clock?

By no means! If polling can be avoided, it should be. In the case of a clock, the value must be updated every second anyway because that’s how time works. However, in this case, D-Bus has a signal that notifies about property changes, so it might be worth trying to use D-Bus directly.

**Comment by linkfrg** [comment]
btw, does other properties work normally (``charging``, ``charged``, ``time_remaining`` etc. other properties that can change)

**Comment by k-amin07** [comment]
nope, it does not update at all. As you can see, the bar still thinks its at 8%, no charging status, even though the laptop is plugged in
![image](https://github.com/user-attachments/assets/8099058c-8fba-47dc-99f2-4c44d7a58806)

after reloading ignis
![image](https://github.com/user-attachments/assets/f1210942-88b7-49d6-897a-0b54d51bd097)

**Comment by linkfrg** [comment]
> no charging status

I didn't add it.
I mean, try this code:
```
from ignis.services.upower import UPowerService

upower = UPowerService.get_default()

for i in upower.batteries:
    i.connect(
        "notify::charging", lambda x, y, i=i: print("Charging status: ", i.charging)
    )
```

**Comment by k-amin07** [comment]
Tried it a couple of times, it returned 100, 99 and 98 across different runs

**Comment by linkfrg** [comment]
> Tried it a couple of times, it returned 100, 99 and 98 across different runs

Are you sure you used the code in my comment above? It is different from the first code. It shouldn't return any numbers, just a boolean value.

**Comment by k-amin07** [comment]
copy-pasted it
![image](https://github.com/user-attachments/assets/c8b20089-681d-4dd2-bf45-9b04bf2313b7)

**Comment by linkfrg** [comment]
> copy-pasted it
> ![image](https://github.com/user-attachments/assets/c8b20089-681d-4dd2-bf45-9b04bf2313b7)
> 
> edited to add: putting this in a python file and running the file itself does not print anything

You need to paste it to the config file

**Comment by k-amin07** [comment]
still nothing. I quit ignis and started it from terminal to see if I get an output there but nothing there either

**Comment by linkfrg** [comment]
I created #26, need testing.

**Comment by linkfrg** [comment]
> However the icon does not change based on charging/discharging state

It is better to continue further discussion directly in #26

**Comment by D3ja-vu** [comment]
i  psutils to get currrent bat percentage and cpu ,even i added the charging indicator and works well for me i can pr this if u want

**Comment by linkfrg** [comment]
> i  psutils to get currrent bat percentage and cpu ,even i added the charging indicator and works well for me i can pr this if u want 

No, thanks.
Official, GObject-based implementation of UPower Service is better.
