### ISSUE TITLE
cannot view Widget.Scroll child

### ISSUE THREAD

**Issue by newor0599** [linkfrg/ignis#27]
### Question

I cannot see the child of a `Widget.Scroll`, its child is a gtkviewport and the child i assigned to scroll is being transferred to gtkviewport, the gtkviewport has a width and height of 0 according to `ignis inspector`

### Python code
```python
Widget.Scroll(
        css_classes = ['main'],
        # child = bluetooth_menu,
        child = Widget.Box(
            child = [Widget.Label(label = str(i+1)) for i in range(10)]
            )
        )
```
### css
```css
.main{
  background: #999;
  padding: 10px;
}
```

### Result

![image](https://github.com/user-attachments/assets/5965da78-d84a-426f-bd40-e2d4d7cb0cf8)

### Child hierarchy
![image](https://github.com/user-attachments/assets/dbf8f47d-98e5-4fc1-bb8f-6f16399be95d)

### Magnify gtkviewport
![image](https://github.com/user-attachments/assets/2723276d-696d-4ef3-b430-7b2910cc6620)

**Comment by linkfrg** [comment]
try setting ``min-height: 100px;`` (``min-width: 100px;``) to your ``Widget.Scroll`` in CSS

**Comment by newor0599** [comment]
Solved, thanks!

**Comment by newor0599** [comment]
Solved, thanks!
