### ISSUE TITLE
Child of box stretched when revealer is expanded sliding up

### ISSUE THREAD

**Issue by newor0599** [linkfrg/ignis#30]
### Question

When a revealer in a box is revealing or hiding its child by sliding up, the other child in the box are being stretch

Child to show with revealer
```python
main_connection_menu = Widget.Box(
        child = [Widget.Revealer(
            child = bt_menu,
            reveal_child = False,
            transition_type = 'slide_up'
            )]
        )
```

Main Box
```python
bar_main = Widget.Box(
        vertical = True,
        child = [
            main_connection_menu,
            Widget.EventBox(
                vertical = True,
                css_classes = ["bar","trigger"],
                on_hover = lambda x: x.child[0].set_reveal_child(True),
                on_hover_lost = lambda x: x.child[0].set_reveal_child(False),
                child = [
                        Widget.Revealer(
                            hexpand = True,
                            valign = 'end',
                            child = bar,
                            transition_type = "slide_up",
                            transition_duration = 500,
                            reveal_child = False,
                        ),
                    ]
                ),
            ]
        )
```

https://github.com/user-attachments/assets/ee1c1df4-bcc5-49ac-87b8-955ccc94f3d5

**Comment by linkfrg** [comment]
Hyprland issue, you can try to disable layer animations for this window using ``layerrule`` in hyprland config.

**Comment by newor0599** [comment]
Its now not stretching, but there's still flicker

https://github.com/user-attachments/assets/848ca916-75fc-42ed-ad72-ae9ba2028b0c

**Comment by newor0599** [comment]
I'm really sorry that I cannot see anything different with my config. I do see a style applied to the return window, but setting a min-height is not an option for me

**Comment by OBLIXi-ON** [comment]
It happens with `AGS` as well. Also what's the `layerrule` to disable layer animation?

**Comment by linkfrg** [comment]
> Also what's the `layerrule` to disable layer animation?

``noanim``

**Comment by newor0599** [comment]
Got it, everything is working as expected now, for anyone having this problem in the future:

## Why it happens
Layer window is being resized, causing the flicker

### Fixes
- Add additional anchor
- - eg. add `top` and `bottom` anchor to window for slide_up animation

### Problem with the fix
The whole screen will be obstructed by the window, causing the problem of unable to interact with other things than the window

### Fix to the problem
Set window input height and input width, you can get the required heigth and width from your widget

**Comment by linkfrg** [comment]
13992dfd16c1668be244499dd7760765de6a69e8 adds `Widget.Window.dynamic_input_region` property, now you can use it to automatically manage the input region based on the size of the child
