### ISSUE TITLE
Setting the position for window

### ISSUE THREAD

**Issue by Bavalionprolate** [linkfrg/ignis#31]
### Description

While exploring and integrating your library, I noticed the absence of a direct function to set the widget window position. Currently, only anchor configuration for the window is available.

It would be beneficial to implement the option to position the window via a parameter, such as `position = [x, y]`, as well as a `set_position(x, y)` method for more flexible layout control.

What you think?

**Comment by linkfrg** [comment]
As I remember, gtk4-layer-shell and the Layer Shell protocol in principle don't allow this. The most you can do is use anchor + margin (margin is currently not available in Ignis).

**Comment by linkfrg** [comment]
Margin properties for Widget.Window added in 5a66ef9

**Comment by Bavalionprolate** [comment]
I apologize for the misunderstanding. I had not fully explored the capabilities of gtk4-layer-shell and assumed that specifying precise window coordinates was feasible, as I had seen similar functionality in eww. It appears that gtk4-layer-shell relies on edge anchoring and margins for window positioning rather than direct coordinate assignment. I regret not considering this aspect earlier.

Thank you for implementing the margin functionality for screen edges — it's a valuable and useful feature.
