### ISSUE TITLE
"Enable/Disable Notifications" in Telegram system tray doesn't work

### ISSUE THREAD

**Issue by imxnasr** [linkfrg/ignis#33]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Related to dotfiles ? *

- [X] I'm sure the problem is related specifically to Ignis.

### Regression?

No

### Version

 ```
Ignis 0.2.dev0
Branch: main
Commit: 5a66ef946f56c5bdfdb2cb042c75ca29c663125b (feat: Widget.Window: add margin properties)
```

### Distro

Arch

### Description

In the system tray telegram menu, Enable/Disable Notifications doesn't work.

### How to reproduce

- Install telegram
- Open it
- Try the tray

**Comment by newor0599** [comment]
Do you mean the system tray provided in the ignis simple bar example?

**Comment by imxnasr** [comment]
Yes.

**Comment by newor0599** [comment]
What did yoy try to disable telegram notifications?

**Comment by imxnasr** [comment]
I tried disabling it through the tray menu and it do nothing.

**Comment by linkfrg** [comment]
Able to reproduce. Strage, but the "Open Telegram" button works normally.

I am currently analyzing the libdbusmenu (gtk3) code and trying to figure out what i missing in my implementation...

**Comment by linkfrg** [comment]
Should be fixed after https://github.com/linkfrg/ignis/commit/2def675b0d33ca4fdeb3f36e0c0a7d228efaad6e
