### ISSUE TITLE
Audio Service not working

### ISSUE THREAD

**Issue by newor0599** [linkfrg/ignis#34]
### Question

I know this is my problem, that's why I'm asking for help. 
### Issue
I want to write a volume bar, but audio service is not getting any speaker
```python
audio = AudioService.get_default()
print(audio.speakers) # output: []
```

### What I tried
1. I have installed pipewire-pulse, because I'm using pipewire as my audio backend
2. I tried to import gvc on a new python project
```python
try:
  from gi.repository import Gvc
except Exception as e:
  print(e)
```
but it return an error when I ran the code
```bash
Namespace Gvc not available
```

I asked chatgpt about the error, It turns out I don't have gvc program in `/usr/lib/girepository-1.0`

## My question
1. Why didn't ignis raise an error?
2. How do I get gvc?

## Info about my audio setup
`pactl info`
```bash
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 83
Tile Size: 65472
User Name: newor
Host Name: newor
Server Name: PulseAudio (on PipeWire 1.2.5)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1b.0.analog-stereo
Default Source: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
Cookie: f535:fa0b
```

**Comment by linkfrg** [comment]
> I want to write a volume bar, but audio service is not getting any speaker\n\naudio = AudioService.get_default()\nprint(audio.speakers) # output: []

You cannot get a list of speakers immediately after the first initialization of AudioService, because Gvc is asynchronous library and getting a speakers list happens for some time in the background. So, you need to connect to the ``notify::speakers`` signal and do your things (print) in a callback.

**Comment by linkfrg** [comment]
> Why didn't ignis raise an error?
Gvc is installed into ``/usr/lib/ignis`` during Ignis installation. And then, in ``__init__.py`` this path (``/usr/lib/ignis``) prepends to GIR search.

**Comment by newor0599** [comment]
Thanks for the explanation, really appreciate!
