### ISSUE TITLE
Control center not opening

### ISSUE THREAD

**Issue by gnussbaum67** [linkfrg/ignis#4]
Hi,

When I click on the cog wheel nothing opens.  I can't change any settings.  

![2024-08-22 16_15_55-Arch  Running  - Oracle VM VirtualBox](https://github.com/user-attachments/assets/cbdbe0fa-cf1c-4201-aa79-f2b0438e6be1)

This is the info in the log:

```
2024-08-22 16:12:23,688 [INFO] Using configuration file: /home/xxxxx/.config/ignis/config.py
2024-08-22 16:12:25,612 [INFO] Applied css: /home/xxxxx/.config/ignis/style.scss
2024-08-22 16:12:25,639 [ERROR] No such monitor with id: 1
2024-08-22 16:12:25,639 [INFO] Ready.
```

Not sure why I'm getting the monitor error either.

Using Arch Linux which is a VirtualBox VM.

**Comment by linkfrg** [comment]
Known issue: #3.
Should be fixed in latest git version, but I have made some breaking changes to Ignis, so i will update dotfiles when i release a new version of Ignis (v0.2).

**Comment by gauravsatish** [comment]
> Known issue: #3. Should be fixed in latest git version, but I have made some breaking changes to Ignis, so i will update dotfiles when i release a new version of Ignis (v0.2).

any eta on the updated dotfiles/Ignis v0.2?
absolutely no pressure, you can take your time, just wondering

**Comment by linkfrg** [comment]
I don't know, the work took a bit longer. For now you can use ignis-git and the [dev](https://github.com/linkfrg/dotfiles/tree/dev) branch of the dotfiles

**Comment by linkfrg** [comment]
> any eta on the updated dotfiles/Ignis v0.2?

eta: now
