### ISSUE TITLE
Add signals to NetworkService

### ISSUE THREAD

**Issue by AndreyDeimos** [linkfrg/ignis#50]
### Description

It would be nice to have signals, like disconnecting from or connecting to an access point, Ethernet, VPN, etc.

**Comment by linkfrg** [comment]
Can you provide a more detailed list of signals you need with descriptions?

**Comment by AndreyDeimos** [comment]
> Can you provide a more detailed list of signals you need with descriptions?

1. New connection via WiFi - notify when your current connection is now a WiFi network or when the access point has changed.
2. New connection via Ethernet - notify when your current connection is now Ethernet.
3. You've disconnected from your current connection - notify if you have disconnected from a network and do not have any other WiFi or Ethernet connections.
4. New VPN connection - notify when you have a new VPN connection or when it has changed.
5. Disconnected from VPN - notify when you have disconnected from a VPN.

**Comment by linkfrg** [comment]
> 1. notify when your current connection is now a WiFi network or when the access point has changed.

There is problem: you can have multiple active (current) connections at the same time. I can just add signal that emits when a new connection via Wi-Fi is activated. The same for Ethernet

> 3. You've disconnected from your current connection - notify if you have disconnected from a network and do not have any other WiFi or Ethernet connections.

Will be emited when amount of active connections < 0

> 5. Disconnected from VPN - notify when you have disconnected from a VPN.
Use [Vpn.is_connected property](https://linkfrg.github.io/ignis/latest/api/services/network.html#ignis.services.network.Vpn.is_connected)

**Comment by linkfrg** [comment]
I added some new signals in #80, can you look at them and check if they meet your needs?

**Comment by AndreyDeimos** [comment]
> I added some new signals in #80, can you look at them and check if they meet your needs?

Yes! Thank you very much!
