### ISSUE TITLE
How to import PIL and other libraries on NixOS?

### ISSUE THREAD

**Issue by TanR314** [linkfrg/ignis#51]
### Question

I am using NixOS

For some reasons when I import PIL ( I did install PIL ) , it is giving me errors, It says
```
ModuleNotFoundError: No module named 'PIL'
```

I am new to python and NixOS, I don't know how to fix it.

edit: It is working on Arch Linux, So the issue is about the ignis package of nixos

**Comment by linkfrg** [comment]
I am not a Nix user and the package wasn't made by me. I can't help you, sorry.

Perhaps someone else in this repo can help you, or you may ask this question in Nix related communities (reddit/discord/etc)

**Comment by TanR314** [comment]
Okay I had to install ignis in this way ( I learned it from chatgpt )
```
    (inputs.ignis.packages.${system}.ignis.overrideAttrs (oldAttrs: {
      propagatedBuildInputs = (oldAttrs.propagatedBuildInputs or []) ++ ( with pkgs; [
        (pkgs.python312.withPackages (ppkgs: [
          ppkgs.materialyoucolor
          ppkgs.pillow
          ppkgs.jinja2
          # Library names
        ]))
      ]);
    }))

```

and it got fixed :)
