### ISSUE TITLE
bluetooth and directory

### ISSUE THREAD

**Issue by Shentxt** [linkfrg/ignis#55]
### Question

I have a question, I read all the documentation but I didn't find anything about a bluetooth service.
I would also like to know how to move __pycache__ to a cache directory or to .ignis, because currently it is created in the .config/ignis directory

**Comment by linkfrg** [comment]
1. Bluetooth Service is a work in progress (see #28)
2. You cannot move ``__pycache__`` to ``~/.ignis``, these directories are created by the Python interpreter and are used to speed up launching
