### ISSUE TITLE
SystemTray Icon doesn't use Gdk.pixbuf

### ISSUE THREAD

**Issue by TanR314** [linkfrg/ignis#61]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Yes

### System Information

 ```
Ignis 0.3.dev0
Branch: 
Commit:  ()
Current desktop: Hyprland

os-release:
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20241207.22c3f2c"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"

```

### Description

In Ignis `item.icon` returns both gdk.pixbuf and icon name. But in ags, I saw that it has both `item.icon` and `item.gIcon` where `item.icon` only returns icon name, while `item.gIcon` only returns gdk.pixbuf.

Now in ags I saw spotify returns both gdk.pixbuf and icon name ( and the icon name doesn't exist ). In Ignis it is returning the string or icon_name instead of gdk.pixbuf. And the icon_name "spotify-linux-32" doesn't exist. It should've return gdk.pixbuf instead of string.

### How to reproduce

I guess ignis's systemtray should give the result for anyone...

### Logs, images, videos, config files, CSS/SCSS files

![image](https://github.com/user-attachments/assets/c4786042-fae7-4808-9a56-f0dd2e3f3d9c)

Since "spotify-linux-32" icon doesn't exist, it gives this warning icon...

**Comment by linkfrg** [comment]
Cannot reproduce
![image](https://github.com/user-attachments/assets/b6c150ad-1777-4490-8004-d2a2fe2397ee)
![image](https://github.com/user-attachments/assets/87b24e90-bf63-4c2c-8dd0-44767a877c1e)
(``GdkPixbuf.Pixbuf`` here for telegram and ``spotify-linux-32`` for spotify accordingly)

Maybe it's something wrong with your spotify installation?

**Comment by linkfrg** [comment]
Oh, i installed ``spotify`` package from AUR

I will check ``spotify-launcher``

**Comment by TanR314** [comment]
Okay the "spotify-linux-32" icon in your screenshot is working because of Papirus Icon Theme I guess, After installing Papirus, it is working on my pc too. But it is using the papirus's "spotify-linux-32" icon instead of `/opt/spotify/icons/spotify-linux-32`

![image](https://github.com/user-attachments/assets/22151328-6fa6-4065-9016-bfb7a1503f2c)

**Comment by linkfrg** [comment]
> Okay the "spotify-linux-32" icon in your screenshot is working because of Papirus Icon Theme I guess, After installing Papirus, it is working on my pc too. But it is using the papirus' "spotify-linux-32" icon instead of `/opt/spotify/icons/spotify-linux-32`

Hmm, you can try using [IgnisApp.add_icons()](https://linkfrg.github.io/ignis/latest/api/app.html#ignis.app.IgnisApp.add_icons) and add custom icon with the name ``spotify-linux-32``

**Comment by TanR314** [comment]
The issue with NixOS is that the paths are incredibly long 🥲. For example, in my case, the path is:  
`/nix/store/ajmabji1my62iihvdkv3wypwixdfan0h-spotify-1.2.48.405.gf2c48e6f/share/spotify/icons/spotify-linux-32.png`.  
(For now, I'll use this path.)  

However, it would be much better if the system tray could automatically detect the icon path. Otherwise, users who don't know about `/opt/spotify/icons/spotify-linux-32` might end up stuck trying to figure out the correct path.

**Comment by linkfrg** [comment]
> The issue with NixOS is that the paths are incredibly long 🥲. For example, in my case, the path is:
> `/nix/store/ajmabji1my62iihvdkv3wypwixdfan0h-spotify-1.2.48.405.gf2c48e6f/share/spotify/icons/spotify-linux-32.png`.
> (For now, I'll use this path.)

I mean add this icon to your config as described in the doc for IgnisApp.add_icons()


> However, it would be much better if the system tray could automatically detect the icon path. Otherwise, users who don't know about `/opt/spotify/icons/spotify-linux-32` might end up stuck trying to figure out the correct path.

Hmm, i agree, i already have some idea about this
