### ISSUE TITLE
Ignis doesn't work after last update

### ISSUE THREAD

**Issue by imxnasr** [linkfrg/ignis#65]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Information

 ```
Ignis 0.3.dev0
Branch: main
Commit: 54b8c6f3e16bd950ae125f4aa67a921071549336 (bruh)
Current desktop: Hyprland

os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

### Description

After last update Ignis doesn't work

### The output after `ignis init`:
```
2024-12-11 17:10:56 [INFO] Using configuration file: /home/username/.config/ignis/config.py
2024-12-11 17:10:58 [INFO] Applied css: /home/username/.config/ignis/style.scss
2024-12-11 17:10:58 [INFO] Ready.
[1]    13439 segmentation fault (core dumped)  ignis init
```

### How to reproduce

Run `ignis init`

**Comment by linkfrg** [comment]
Cannot reproduce
Can you share your config?

**Comment by imxnasr** [comment]
Invited you to my dotfiles repo.

**Comment by linkfrg** [comment]
hmmm, did you tried cleaning ``__pycache__`` directories?
also tip: add ``__pycache__`` to .gitignore

**Comment by imxnasr** [comment]
Tried now and didn't work.

**Comment by linkfrg** [comment]
I just updated the system (glib was updated) and still can't reproduce

Would it be difficult for you to try on a fresh system?

**Comment by linkfrg** [comment]
Try running: ``GSK_RENDERER=ngl ignis init``

**Comment by imxnasr** [comment]
Yes, it worked!

**Comment by linkfrg** [comment]
btw
- what version of Hyprland do you use (git or non-git)?
- what GPU do use?
- what version of gtk4-layer-shell is installed?

**Comment by imxnasr** [comment]
Update `ignis-git` now through the aur and it works now without `GSK_RENDERER=ngl`

**Comment by linkfrg** [comment]
> Update `ignis-git` now through the aur and it works now without `GSK_RENDERER=ngl`

magic

So, this issue can be closed?

**Comment by imxnasr** [comment]
Hyprland: non-git
GPU:
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
	DeviceName:  Onboard IGD
	Subsystem: Dell Device 07be
--
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
	Subsystem: Dell Device 07be
	Kernel driver in use: nvidia
```
gtk4-layer-shell: 1.0.4-1

**Comment by imxnasr** [comment]
> So, this issue can be closed?

Sure.

**Comment by imxnasr** [comment]
Thank you so much.
