### ISSUE TITLE
Add debounce to Utils.

### ISSUE THREAD

**Issue by minhnbnt** [linkfrg/ignis#69]
### Description

I think it would be great if we include Utils.debounce to create debounced function that delay function calls until a set time elapses after the last function call.

**Comment by linkfrg** [comment]
I think it's better to add ``delay`` to ``Utils.Poll``

**Comment by minhnbnt** [comment]
Can you take a look how debounce works?

https://github.com/user-attachments/assets/0e013e63-1bc2-4ecc-ad90-483684f07c2d

**Comment by newor0599** [comment]
I just use Utils.Timeout
```python
timeout =  None
def timeout_brightness():
  global timeout
  if timeout != None:
    timeout.cancel()
  timeout = Utils.Timeout(1000, set_brightness(value))
```

**Comment by linkfrg** [comment]
> Can you take a look how debounce works?

Oh, now I understand

You can share your code for debounce here or make a Pull Request

**Comment by minhnbnt** [comment]
I think this is the most elegant way :)))

```python3
from typing import Callable

from ignis.utils import Utils


class Debounce:
    def __init__(self, ms: int, fn: Callable) -> None:
        self._timeout = Utils.Timeout(0, lambda: None)
        self._fn, self._ms = fn, ms

    def __call__(self, *args, **kwargs):
        self._timeout.cancel()
        self._timeout = Utils.Timeout(self._ms, lambda: self._fn(*args, **kwargs))


def debounce_decorator(ms: int):
    def decorate_function(func):
        return Debounce(ms, func)

    return decorate_function
```
