### ISSUE TITLE
Nix package disables access to system PATH

### ISSUE THREAD

**Issue by campbellcole** [linkfrg/ignis#70]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Information

```
Ignis 0.3.dev0
Branch: 
Commit:  ()
Current desktop: Hyprland

os-release:
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20241211.5d67ea6"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"
```

### Description

Attempting to use a binary using `Utils.exec_sh` that is accessible via CLI does not work in many cases because of the wrapper created in the Nix derivation.

I learned this attempting to use the config at [linkfrg/dotfiles](https://github.com/linkfrg/dotfiles), and when using the launcher, the `Utils.exec_sh("xdg-settings get default-web-browser")` call cannot find the `xdg-settings` binary even though I can use this command via CLI.

After poking around I saw the `wrapProgram` invocation with a hardcoded `PATH`. It seems to try to fix this by adding `:$PATH` at the end but this fails to include:
- **`/run/wrappers/bin`**
- `$HOME/.nix-profile/bin`
- `/nix/profile/bin/`
- `$HOME/.local/state/nix/profile/bin`
- **`/etc/profiles/per-user/$USER/bin`**
- `/nix/var/nix/profiles/default/bin`
- **`/run/current-system/sw/bin`**

On my system, only the bold paths exist so I assume those are the most important, but I admit I don't fully understand how these work and what the appropriate way to add these to the binary's `PATH` is.

**Edit:** Just wanted to clarify that despite adding `:$PATH` to the `wrapProgram` invocation, it appears this variable is evaluated at build time and does not inherit the `PATH` of the parent process when executed. I don't know if this was intentional, but I'd imagine a potential fix would be to explicitly inherit the path somehow. No idea how to do this using `wrapProgram` though.

### How to reproduce

1. Install `ignis` using the Nix derivation
2. Use `Utils.exec_sh('xdg-settings get default-web-browser')`
3. Note the returned object only contains data in stderr: `line 1: xdg-settings: command not found`
4. Attempt to run `xdg-settings get default-web-browser` from CLI
5. Note that it works (assuming it's installed, not sure why it is on my system but it is)

**Comment by linkfrg** [comment]
I don't use Nix and the package for it was created by not me, but by contributors

Can't assist you with that, sorry
I would be glad if you would try to solve this issue and make a pull request
