### ISSUE TITLE
[Question] Converting Polled Value Datatypes to Work for Both a Label and a Scale.

### ISSUE THREAD

**Issue by RoidedSasquatch** [linkfrg/ignis#85]
### Question

I am trying to poll my CPU usage percent using Psutil by storing the result in an Ignis Variable and then binding the value to the label or value of the scale. The problem is I cannot convert the value returned by the Poll callback  to be used in both widgets. If I format the callback function as a String it works properly for the label but then I cannot convert back to numeric to use the value for the scale. The same is true if I do not format and just have the callback return the value returned by Psutil. Then I the scale will work correctly but I cannot convert the value to a String for use with the label. I could just create two separate polls but this seems unnecessary. I'm probably missing something really obvious here but nothing I have tried has worked, so I have turned to Issues.

**Comment by linkfrg** [comment]
Please share your code

**Comment by RoidedSasquatch** [comment]
After taking some time to rethink things I realized I had over-complicated things and have figured out a solution! Closing this issue!
