### ISSUE TITLE
Error thrown upon subsequent connects to password-protected WiFi

### ISSUE THREAD

**Issue by regenman** [linkfrg/ignis#88]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Information

 ```
$ ignis systeminfo
Ignis 0.3.dev0
Branch: main
Commit: 410fae1ec996b9d64127578621c0fa0ab7b0d6ff (WifiDevice.is_connected: use bool() instead of not not)
Current desktop: niri

os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

### Description

```
File "/home/ns/.config/ignis/modules/control_center/wifi.py", line 14, in <lambda>
    on_click=lambda x: access_point.connect_to_graphical(),
                    │  │            └ <function WifiAccessPoint.connect_to_graphical at 0x73b255e420c0>
                    │  └ <access_point.WifiAccessPoint object at 0x73b2569aca40 (ignis+services+network+access_point+WifiAccessPoint at 0x59ff84daf980)>
                    └ <wifi.WifiNetworkItem object at 0x73b2541df300 (modules+control_center+wifi+WifiNetworkItem at 0x59ff85e5dee0)>

  File "/usr/lib/python3.13/site-packages/ignis/services/network/access_point.py", line 248, in connect_to_graphical
    WifiConnectDialog(self)
    │                 └ <access_point.WifiAccessPoint object at 0x73b2569aca40 (ignis+services+network+access_point+WifiAccessPoint at 0x59ff84daf980)>
    └ <class 'ignis.services.network.wifi_connect_dialog.WifiConnectDialog'>
  File "/usr/lib/python3.13/site-packages/ignis/services/network/wifi_connect_dialog.py", line 14, in __init__
    super().__init__(
  File "/usr/lib/python3.13/site-packages/ignis/widgets/regular_window.py", line 33, in __init__
    app.add_window(namespace, self)
    │   │          │          └ <wifi_connect_dialog.WifiConnectDialog object at 0x73b23297d900 (ignis+services+network+wifi_connect_dialog+WifiConnectDialog...
    │   │          └ 'wifi_connect'
    │   └ <function IgnisApp.add_window at 0x73b2575dfd80>
    └ <app.IgnisApp object at 0x73b2575ff580 (ignis+app+IgnisApp at 0x59ff8429a2c0)>
  File "/usr/lib/python3.13/site-packages/ignis/app.py", line 410, in add_window
    raise WindowAddedError(window_name)
          │                └ 'wifi_connect'
          └ <class 'ignis.exceptions.WindowAddedError'>

ignis.exceptions.WindowAddedError: Window already added: "wifi_connect"

```

### How to reproduce

1. Use the control center to connect to a password protected WiFi network. This will trigger an authentication dialogue, either fill in the password or cancel the operation.
2. Again from the control center, attempt to connect to a password protected network. The authentication dialogue will show up, but ignis will throw an error.

**Comment by linkfrg** [comment]
try #88

**Comment by regenman** [comment]
> try #88

With this change, it's slightly better but still not quite good: on the first connect attempt to every ssid, the dialogue show up as it should. But on a second attempt to connect to a previously attempted ssid (eg. after a failed attempt), clicking the ssid does not trigger the dialogue, nothing happens, no errors, and the wifi stays connected to the previous ssid.

**Comment by linkfrg** [comment]
> With this change, it's slightly better but still not quite good: on the first connect attempt to every ssid, the dialogue show up as it should. But on a second attempt to connect to a previously attempted ssid (eg. after a failed attempt), clicking the ssid does not trigger the dialogue, nothing happens, no errors, and the wifi stays connected to the previous ssid.

can you try after cb68131fd8c649ff90f7b143cedc251d27bd5da2?

**Comment by linkfrg** [comment]
> EDIT: the password dialogue shows up for networks that NM already has a stored secret for, normally I would expect to not have to enter a password in this case (but this behaviour might have been there before this PR)

A check for a stored secret is not implemented yet

**Comment by regenman** [comment]
> can you try after [cb68131](https://github.com/linkfrg/ignis/commit/cb68131fd8c649ff90f7b143cedc251d27bd5da2)?

Seems to work as expected now, thank you!

**Comment by regenman** [comment]
> A check for a stored secret is not implemented yet

Are you planning to implement this, or should I create a separate feature request?

**Comment by linkfrg** [comment]
> Are you planning to implement this, or should I create a separate feature request?

Yes, i am
but you can open a separate feature request so that I don’t forget
