### ISSUE TITLE
Hyprland service cause UnicodeDecodeError exception

### ISSUE THREAD

**Issue by minhnbnt** [linkfrg/ignis#91]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Information

 ```
Ignis 0.3
Branch: 
Commit: 959815bd2aa15c223a1a424388f7b20660072c03 (version: bump to 0.3)
Current desktop: Hyprland

os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

### Description

Hyprland socket can return invalid UTF-8 character, which calling `.decode()` will throws UnicodeDecodeError.

We need to handle this by catching the exception or using `errors="replace"` or `errors="ignore"` when decoding the response.
https://docs.python.org/3/howto/unicode.html#the-string-type

### How to reproduce

It just randomly appear after keep ignis running very long time, I can't reproduce this.

### Logs, images, videos, config files, CSS/SCSS files

![20241227_19h54m51s_grim](https://github.com/user-attachments/assets/3c8cdb63-1eaf-49ec-8dac-703d0dc4b1bb)

**Comment by linkfrg** [comment]
should be fixed after bab890ca52b2e0ef3fe62e2fbd83dcc133d1a800
