### ISSUE TITLE
Segfault Using Example Bar

### ISSUE THREAD

**Issue by PacificViking** [linkfrg/ignis#93]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

No

### System Information

 ```
Ignis 0.3.dev0
Branch:
Commit:  ()
Current desktop: Hyprland

os-release:
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240911.4f807e8"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"
```

### Description

Segfault when I press the "power button" on the bar. (This issue is present if any menu item is in the power menu. If there were none, an empty menu appears with no error.)

### How to reproduce

run ```ignis init``` with /example/bar copied into ~/.config/ignis
click the "power button" (on the right)

### Logs, images, videos, config files, CSS/SCSS files

[ignis.log](https://github.com/user-attachments/files/18268153/ignis.log)
[ignis_segfault.log](https://github.com/user-attachments/files/18268154/ignis_segfault.log)

These logs were generated with ```PYTHONFAULTHANDLER=1 ignis init --debug >>ignis_segfault.log 2>&1```

**Comment by linkfrg** [comment]
cannot reproduce on archlinux
1. What version of GTK are you using?
2. What is the version of gtk4-layer-shell?
3. Can you try running with `` GSK_RENDERER=ngl ignis init`` or `` GSK_RENDERER=gl ignis init``

**Comment by PacificViking** [comment]
Now that I understand that my gtk4 version matters I removed the nixpkgs follows line from my flake and it works with both commands above! Sorry for the dumb bug report and thank you for the help!
