### ISSUE TITLE
How to bind Hyprland workspace name?

### ISSUE THREAD

**Issue by ArtemChandragupta** [linkfrg/ignis#94]
### Question

I want to use [hyprland-autoname-workspaces](https://github.com/hyprland-community/hyprland-autoname-workspaces). To have it working, I need to make workspace button labels update on every workspace name updates. How would I do that?

In AGS2 I can do this:

```js
import { bind } from "astal"
import Hyprland from "gi://AstalHyprland";

export function WorkspacesModule() {
  const hypr = Hyprland.get_default();

  return (
    <box className = "WorkspaceModule"> 
      {bind(hypr, "workspaces").as(
	workspaces => workspaces.sort((a, b) => a.id - b.id).map(workspace => (
	  <button 
	    className = {bind(hypr, "focusedWorkspace").as(
	      x => x.id === workspace.id ? "focused-workspace workspace-btn" : "workspace-btn"
	    )}
	    cursor = "pointer"
	    onClicked = {() => hypr.message(`dispatch workspace ${workspace.id}`)}
	  >
	    {bind(workspace, "name").as(name => name)}
	  </button>
	))
      )}
    </box>
  );
}
```

Based on examples in documentation, I tried to do this, but this code does not work because `bind` can't accept lists:

```py
def hyprland_workspace_button(workspace: dict) -> Widget.Button:
    widget = Widget.Button(
        css_classes=["workspace"],
        on_click=lambda x, id=workspace["id"]: hyprland.switch_to_workspace(id),
        child=Widget.Label(
            # label=str(workspace["name"]),
            label=hyprland.workspaces.bind("name", lambda value: str(value))
        ),
    )
    if workspace["id"] == hyprland.active_workspace["id"]:
        widget.add_css_class("active")

    return widget
```

**Comment by linkfrg** [comment]
> Based on examples in documentation, I tried to do this, but this code does not work because `bind` can't accept lists

yep, python ``list`` doesn't have ``.bind()`` method
Seems like AGS2/Astal provides GObject-based object for each Hyprland workspace, while Ignis provides a simple python dict

For implementing this in Ignis, it requires major changes to Hyprland Service. In fact, I plan to do this, but in v0.5

**Comment by linkfrg** [comment]
It took... a little bit more time than I expected, but anyway it's done
#171 moves Hyprland Service to use GObjects and #172 adds updating workspaces names on ``"renameworkspace"`` event.
#172 requires additional testing before merging

**Comment by ArtemChandragupta** [comment]
Interesting. Can I help you?

**Comment by linkfrg** [comment]
> Interesting. Can I help you?

Yep!
