### ISSUE TITLE
Directly use `bluetoothctl` for bluetooth client

### ISSUE THREAD

**Issue by AstrickHarren** [linkfrg/ignis#96]
### Description

First of all, love your amazing gtk4 shell here! Very simple and stupid (in the best way) :heart: 

I'm trying to build a bluetooth quick settings the way you did in your dotfiles, but I don't want to install Gnome bluetooth as apparently that is what has been used for bluetooth client.  I could be wrong but I feel like if I'm using Hyprland as WM, it kinda defeats the purpose.

What do you think?

**Comment by linkfrg** [comment]
Gnome Bluetooth is just a library, it uses bluez and provides GObject bindings to it, nothing special. It is connected with gnome only by name

``bluetoothctl`` is cli utility, one of the principles of Ignis is to avoid using external shell programs whenever possible, so no, we will continue using gnome-bluetooth-3.0

**Comment by AstrickHarren** [comment]
I think you're right, closing this issue.
